
package com.gemsrobotics.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj HomeAuto = new ChoreoTraj(
	    "HomeAuto",
	    OptionalInt.empty(),
	    3.58362,
	    new Pose2d(6.32, 1.565, Rotation2d.fromRadians(2.175)),
	    new Pose2d(3.072, 2.61, Rotation2d.fromRadians(0.8))
	);
	public static final ChoreoTraj LeftBasicShootAuto = new ChoreoTraj(
	    "LeftBasicShootAuto",
	    OptionalInt.empty(),
	    5.42007,
	    new Pose2d(3.437, 5.574, Rotation2d.fromRadians(-0.793)),
	    new Pose2d(2.793, 5.502, Rotation2d.fromRadians(-2.393))
	);
	public static final ChoreoTraj RightBasicShootAuto = new ChoreoTraj(
	    "RightBasicShootAuto",
	    OptionalInt.empty(),
	    5.31127,
	    new Pose2d(3.456, 2.514, Rotation2d.fromRadians(0.767)),
	    new Pose2d(2.829, 2.531, Rotation2d.fromRadians(2.416))
	);
	public static final ChoreoTraj LeftSkipBump = new ChoreoTraj(
	    "LeftSkipBump",
	    OptionalInt.empty(),
	    4.54752,
	    new Pose2d(5.755, 5.513, Rotation2d.fromRadians(-0.859)),
	    new Pose2d(2.793, 5.502, Rotation2d.fromRadians(-2.393))
	);
	public static final ChoreoTraj RightSkipBump = new ChoreoTraj(
	    "RightSkipBump",
	    OptionalInt.empty(),
	    4.49895,
	    new Pose2d(5.731, 2.42, Rotation2d.fromRadians(0.8)),
	    new Pose2d(2.829, 2.531, Rotation2d.fromRadians(2.416))
	);
	public static final ChoreoTraj LeftSkipBump2 = new ChoreoTraj(
	    "LeftSkipBump2",
	    OptionalInt.empty(),
	    5.51133,
	    new Pose2d(2.793, 5.502, Rotation2d.fromRadians(-0.689)),
	    new Pose2d(2.937, 5.431, Rotation2d.fromRadians(-2.271))
	);
	public static final ChoreoTraj RightSkipBump2 = new ChoreoTraj(
	    "RightSkipBump2",
	    OptionalInt.empty(),
	    5.34297,
	    new Pose2d(2.829, 2.531, Rotation2d.fromRadians(0.639)),
	    new Pose2d(2.829, 2.531, Rotation2d.fromRadians(2.416))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("HomeAuto", HomeAuto),
		Map.entry("LeftBasicShootAuto", LeftBasicShootAuto),
		Map.entry("RightBasicShootAuto", RightBasicShootAuto),
		Map.entry("LeftSkipBump", LeftSkipBump),
		Map.entry("RightSkipBump", RightSkipBump),
		Map.entry("LeftSkipBump2", LeftSkipBump2),
		Map.entry("RightSkipBump2", RightSkipBump2)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
