package com.gemsrobotics.subsystems.swerve;

import static edu.wpi.first.units.Units.*;
import static java.lang.Math.*;

import java.util.Arrays;
import java.util.Optional;
import java.util.function.Supplier;
import java.util.stream.Stream;

import choreo.Choreo;
import choreo.auto.AutoFactory;
import choreo.trajectory.SwerveSample;
import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import com.gemsrobotics.Constants;
import com.gemsrobotics.RobotState;
import com.gemsrobotics.lib.StatusSignalManager;
import com.gemsrobotics.lib.math.GeometryUtil;
import com.gemsrobotics.vision.PoseEstimate;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.*;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.networktables.DoubleArrayPublisher;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.units.measure.AngularVelocity;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.lib.BLine.FollowPath;
import frc.robot.lib.BLine.Path;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public final class CommandSwerveDrivetrain extends SwerveConstants.TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    private final Telemetry m_logger;
    private final SwerveRequest.ApplyFieldSpeeds m_driveSpeedsRequest;
    private final PIDController m_pathXController;
    private final PIDController m_pathYController;
    private final PIDController m_pathThetaController;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    private final DoubleArrayPublisher m_intakeCornersSpeedsPublisher;
    private final StructPublisher<Pose2d> m_goalPosePublisher;
    private final StructPublisher<Rotation2d> m_tiltPublisher;
    private final StructPublisher<Rotation3d> m_rotation3dPublisher;
    private final StructPublisher<Pose3d> m_robotNormal;

    //region SysId
    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.ApplyRobotSpeeds m_robotSpeedsRequest;
    private final FollowPath.Builder m_autoPathBuilder, m_teleopPathBuilder;
    private final RobotState m_robotState;
    private final StatusSignal<AngularVelocity> m_yawVelocity;

    private PIDController makePController(final double P) {
        return new PIDController(P, 0.0, 0.0);
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            final StatusSignalManager signalManager,
            final RobotState robotState,
            final SwerveDrivetrainConstants drivetrainConstants,
            final SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);

        m_driveSpeedsRequest = new SwerveRequest.ApplyFieldSpeeds();
        //These PID values may need to be changed
        m_pathXController = new PIDController(6.0, 0, 0);
        m_pathYController = new PIDController(6.0, 0, 0);
        m_pathThetaController = new PIDController(5, 0, 0.2);
        m_pathThetaController.enableContinuousInput(-PI, PI);

        m_robotState = robotState;
        m_yawVelocity = getPigeon2().getAngularVelocityZWorld(false);
        m_yawVelocity.setUpdateFrequency(250);

        final NetworkTable stateTable = NetworkTableInstance.getDefault().getTable("swerve_state");

        // do two forms of telemetry here. submit the CTRE stuff to dashboard, and also RobotState
        // notably, we use the timestamps from the swerve odometry thread (timesynced)
        // and insert the gyro velocity over the odometerized velocity
        m_logger = new Telemetry(stateTable);
        registerTelemetry(state -> {
            m_logger.telemeterize(state);

            // submit info to RobotState
            final SwerveDriveState swerveState = getStateCopy();
            final double sampleTime = Utils.currentTimeToFPGATime(swerveState.Timestamp);
            final double omegaRadiansPerSecond = m_yawVelocity.refresh().getValue().in(RadiansPerSecond);
            final ChassisSpeeds measuredChassisSpeeds = getKinematics().toChassisSpeeds(swerveState.ModuleStates);
            final ChassisSpeeds fusedChassisSpeeds = new ChassisSpeeds(
                    measuredChassisSpeeds.vxMetersPerSecond,
                    measuredChassisSpeeds.vyMetersPerSecond,
                    omegaRadiansPerSecond);

            m_robotState.addDriveSample(
                    sampleTime,
                    swerveState.Pose,
                    omegaRadiansPerSecond,
                    fusedChassisSpeeds);
        });

        m_robotSpeedsRequest = new SwerveRequest.ApplyRobotSpeeds();
        m_robotSpeedsRequest.SteerRequestType = SwerveModule.SteerRequestType.MotionMagicExpo;
        m_robotSpeedsRequest.DriveRequestType = SwerveModule.DriveRequestType.Velocity;
        // notably, do NOT provide a pose reset function. we don't do that here
        m_autoPathBuilder = new FollowPath.Builder(
                this,
                () -> getState().Pose,
                () -> getState().Speeds,
                this::setRobotSpeeds,
                makePController(5.0),
                makePController(4.0),
                makePController(3.0)
        ).withDefaultShouldFlip();
        m_teleopPathBuilder = new FollowPath.Builder(
                this,
                () -> getState().Pose,
                () -> getState().Speeds,
                this::setRobotSpeeds,
                makePController(5.0),
                makePController(4.0),
                makePController(3.0)
        );

        Path.setDefaultGlobalConstraints(new Path.DefaultGlobalConstraints(
                Constants.MAX_SPEED,
                Constants.MAX_ACCELERATION,
                toDegrees(Constants.MAX_ANGULAR_RATE),
                toDegrees(Constants.MAX_ANGULAR_RATE) / 2.0,
                0.05,
                5.0,
                0.3
        ));

        m_rotation3dPublisher = stateTable.getStructTopic("rotation3d", Rotation3d.struct).publish();
        m_robotNormal = stateTable.getStructTopic("robot_normal", Pose3d.struct).publish();
        m_intakeCornersSpeedsPublisher = stateTable.getDoubleArrayTopic("intake_corner_speeds").publish();
        m_tiltPublisher = stateTable.getStructTopic("tilt", Rotation2d.struct).publish();
        m_goalPosePublisher = stateTable.getStructTopic("tracking_pose", Pose2d.struct).publish();
        m_goalPosePublisher.setDefault(new Pose2d());

        // TODO add NT4 logging hooks
        // use this for logging hooks
        final NetworkTable bLineTable = stateTable.getSubTable("bline");
        FollowPath.setBooleanLoggingConsumer(pair -> {
        });
        FollowPath.setDoubleLoggingConsumer(pair -> {
        });
        FollowPath.setPoseLoggingConsumer(pair -> {
        });
        FollowPath.setTranslationListLoggingConsumer(pair -> {
        });

        // power tracking
        final NetworkTable motorsTable = NetworkTableInstance.getDefault().getTable("swerve_motors");
        final TalonFX[] moduleMotors = Arrays.stream(getModules()).flatMap(module ->
            Stream.of(module.getDriveMotor(), module.getSteerMotor())).toArray(TalonFX[]::new);
        signalManager.registerPowerTracking(Constants.CAN.kMAIN_BUS, motorsTable, moduleMotors);

        // sim
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Creates a new auto factory for this drivetrain.
     *
     * @return AutoFactory for this drivetrain
     */
    public AutoFactory createAutoFactory() {
        return createAutoFactory((sample, isStart) -> {});
    }

    /**
     * Creates a new auto factory for this drivetrain with the given
     * trajectory logger.
     *
     * @param trajLogger Logger for the trajectory
     * @return AutoFactory for this drivetrain
     */
    public AutoFactory createAutoFactory(final Choreo.TrajectoryLogger<SwerveSample> trajLogger) {
        return new AutoFactory(
                () -> getState().Pose,
                this::resetPose,
                this::setTrajectorySample,
                true,
                this,
                trajLogger);
    }

    private void setRobotSpeeds(final ChassisSpeeds chassisSpeeds) {
        setControl(m_robotSpeedsRequest.withSpeeds(chassisSpeeds));
    }

    public void setTrajectorySample(final SwerveSample sample) {
            m_goalPosePublisher.set(sample.getPose());
            var pose = getState().Pose;

            var targetSpeeds = sample.getChassisSpeeds();
            targetSpeeds.vxMetersPerSecond += m_pathXController.calculate(pose.getX(), sample.x);
            targetSpeeds.vyMetersPerSecond += m_pathYController.calculate(pose.getY(), sample.y);
            targetSpeeds.omegaRadiansPerSecond += m_pathThetaController.calculate(pose.getRotation().getRadians(), sample.heading);

            setControl(m_driveSpeedsRequest.withSpeeds(targetSpeeds)
                    .withWheelForceFeedforwardsX(sample.moduleForcesX())
                    .withWheelForceFeedforwardsY(sample.moduleForcesY()));
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    @Override
    public void periodic() {
        final SwerveDriveState myState = getState();
        m_intakeCornersSpeedsPublisher.set(new double[] {
                GeometryUtil.magnitude(GeometryUtil.transformVelocity(myState.Speeds, Constants.INTAKE_CORNER_NW, myState.Pose.getRotation())),
                GeometryUtil.magnitude(GeometryUtil.transformVelocity(myState.Speeds, Constants.INTAKE_CORNER_NW, myState.Pose.getRotation()))
        });
        m_tiltPublisher.set(getTilt());
        m_rotation3dPublisher.set(getRotation3d());

        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    public AngularVelocity getYawVelocity() {
        return m_yawVelocity.getValue();
    }

    private static final Translation3d ROBOT_NORMAL = new Translation3d(0.0, 0.0, 1.0);

    /**
     * @return the unsigned 3d-tilt of the robot, combining yaw, pitch, and roll
     */
    public Rotation2d getTilt() {
        final Translation3d currentNormal = ROBOT_NORMAL.rotateBy(getRotation3d());
        return Rotation2d.fromRadians(acos(currentNormal.getZ()));
    }

    public boolean isFlat() {
        return abs(getTilt().getDegrees() - 90) < 3.0;
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(final double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public void acceptPoseMeasurement(final PoseEstimate estimate) {
        if (Constants.Vision.ACCEPT_VISION_MEASUREMENTS) {
            final PoseEstimate correctEstimate;
//            if (estimate.variance().get(2, 0) >= Constants.Vision.HIGH_VARIANCE || estimate.tagCount() < 2 || DriverStation.isEnabled()) {
            if (estimate.variance().get(2, 0) >= Constants.Vision.HIGH_VARIANCE || DriverStation.isEnabled()) {
                // insert the known heading reading
                // rather than hitting the pose estimator with a heading with a high variance
                // this prevents spiraling off of the field
                final var poseSample = samplePoseAt(estimate.timestampSeconds());
                if (poseSample.isEmpty()) {
                    return;
                }

                final Rotation2d newRotation = poseSample.get().getRotation();
                final Matrix<N3, N1> correctVariance = estimate.variance().copy();
                correctVariance.set(2, 0, 0.0);
                correctEstimate = new PoseEstimate(
                        estimate.timestampSeconds(),
                        new Pose2d(estimate.fieldToVehicle().getTranslation(), newRotation),
                        correctVariance,
                        estimate.tagCount());
            } else {
                correctEstimate = estimate;
            }

            addVisionMeasurement(
                    correctEstimate.fieldToVehicle(),
                    correctEstimate.timestampSeconds(),
                    correctEstimate.variance());
        }
    }

    public static FieldCentricFacingAngleWithIntakeLimiting makeAimingRequest() {
        final FieldCentricFacingAngleWithIntakeLimiting aimingRequest = new FieldCentricFacingAngleWithIntakeLimiting();
        aimingRequest.DriveRequestType = SwerveModule.DriveRequestType.Velocity;
        aimingRequest.ForwardPerspective = SwerveRequest.ForwardPerspectiveValue.BlueAlliance;
        aimingRequest.SteerRequestType = SwerveModule.SteerRequestType.MotionMagicExpo;
//        aimingRequest.HeadingController.setPID(12.0, 0.0, 0.7);
        aimingRequest.HeadingController.setPID(9.0, 0.0, 0.0);
        return aimingRequest;
    }

    public FollowPath.Builder getAutoBlineBuilder() {
        return m_autoPathBuilder;
    }

    public FollowPath.Builder getTeleopBlineBuilder() {
        return m_teleopPathBuilder;
    }
}
